### ISSUE TITLE
After delete the file which upload still on hover showing deleted file value

### ISSUE THREAD

**Issue by aravindhan32** [progtarek/angular-drag-n-drop-directive#1]
Please find the attachement
![Untitled](https://user-images.githubusercontent.com/10739490/76399988-96dc6000-63a5-11ea-90a0-88e12bc8120c.png)

**Comment by progtarek** [comment]
Hi @aravindhan32, Thanks for your constructive contribution, this issue has been fixed now, you can check the commit [here](https://github.com/progtarek/angular-drag-n-drop-directive/commit/735a7f1cbcd3d49becbdb286d41c226c259cb1f2)
